### ISSUE TITLE
can't build module in gnuradio 3.8

### ISSUE THREAD

**Issue by AllisonOge** [sandialabs/gr-pdu_utils#3]
Only one test out of 31 passed while building the module with cmake and the block is the qt_pdu_source block. Can this be resolved, if yes how soon please? Thanks. I am personally interested in the tags_to_pdu block

**Comment by jacobgilbert-snl** [comment]
Can you give me some info (OS, gcc version, GR version) so I can better help you? These should build on 3.8 and pass QA.

**Comment by AllisonOge** [comment]
I'm using GNU Radio version 3.8, parrot OS and GCC version 9.3

**Comment by jacobgilbert-snl** [comment]
This is a problem with the overloaded stop() method in the message emitter block. It seems to be apparent in gcc9 so Ubuntu 20.04 is also affected. You can fix it by adding `return true;` to that block like so:

```
bool message_emitter_impl::stop()
{
  GR_LOG_INFO(d_logger, boost::format("Message emitter sent %d messages") % d_n_msgs);
  return true;
}
```

I’ll get a fix when I am able.

**Comment by jacobgilbert-snl** [comment]
@AllisonOge - can you confirm this was addressed with bcffccf8002a770aafec83d8f052b3e643bfc574? Thanks.

**Comment by AllisonOge** [comment]
So sorry for the delay in checking your solution. I had my parrot OS
upgraded recently and it messed up a lot of things in my system which I
think is also part of the reasons I couldn't build your module properly.
However before I will resolve that which I have been working on the whole
day I will build your module on my other laptop with an older version of
parrot and give you my feedback. I'm so sorry for keeping you waiting but
sometimes Linux can be fustrating to resolve

**Comment by AllisonOge** [comment]
`The CXX compiler identification is GNU 9.3.0
-- The C compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type not specified: defaulting to release.
-- Found LOG4CPP: /usr/lib/x86_64-linux-gnu/liblog4cpp.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Checking for module 'gmp'
--   Found gmp, version 6.2.0
-- Found GMP: /usr/lib/x86_64-linux-gnu/libgmpxx.so  
-- Checking for module 'mpir >= 3.0'
--   No package 'mpir' found
-- Could NOT find MPIR (missing: MPIRXX_LIBRARY MPIR_LIBRARY MPIR_INCLUDE_DIR) 
-- Found MPLIB: /usr/lib/x86_64-linux-gnu/libgmpxx.so  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Boost: /usr/include (found suitable version "1.67.0", minimum required is "1.67.0") found components: date_time program_options filesystem system regex thread unit_test_framework chrono atomic 
-- Found VOLK: Volk::volk  
-- User set python executable /usr/bin/python3
-- Found PythonInterp: /usr/bin/python3 (found version "3.8.2") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found suitable exact version "3.8.2") 
-- Checking for module 'fftw3f >= 3.0'
--   Found fftw3f , version 3.3.8
-- Found FFTW3f: /usr/lib/x86_64-linux-gnu/libfftw3f.so  
-- Found Git: /usr/bin/git  
-- Extracting version information from git describe...
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.16") found components: doxygen dot 
-- Using install prefix: /usr/local
-- Building for version: v1.2-7-gbcffccf8 / 1.0.0git
-- No C++ unit tests... skipping
-- 
-- Checking for module SWIG
-- Disabling SWIG because version check failed.
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found version "3.8.2") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/allisonogechukwu/projectDSA/gr-pdu_utils/build
` 
This is my result with cmake in the build folder. I cloned the repository again since you mage the changes you said but it is the same result

**Comment by AllisonOge** [comment]
@jacobgilbert-snl I tried building it again with the changes you sent to me as well as the update you added to the repo but my result is the same. I have the result of running the cmake command ishown below so you can help me better

> The CXX compiler identification is GNU 9.3.0
-- The C compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type not specified: defaulting to release.
-- Found LOG4CPP: /usr/lib/x86_64-linux-gnu/liblog4cpp.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Checking for module 'gmp'
--   Found gmp, version 6.2.0
-- Found GMP: /usr/lib/x86_64-linux-gnu/libgmpxx.so  
-- Checking for module 'mpir >= 3.0'
--   No package 'mpir' found
-- Could NOT find MPIR (missing: MPIRXX_LIBRARY MPIR_LIBRARY MPIR_INCLUDE_DIR) 
-- Found MPLIB: /usr/lib/x86_64-linux-gnu/libgmpxx.so  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Boost: /usr/include (found suitable version "1.67.0", minimum required is "1.67.0") found components: date_time program_options filesystem system regex thread unit_test_framework chrono atomic 
-- Found VOLK: Volk::volk  
-- User set python executable /usr/bin/python3
-- Found PythonInterp: /usr/bin/python3 (found version "3.8.2") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found suitable exact version "3.8.2") 
-- Checking for module 'fftw3f >= 3.0'
--   Found fftw3f , version 3.3.8
-- Found FFTW3f: /usr/lib/x86_64-linux-gnu/libfftw3f.so  
-- Found Git: /usr/bin/git  
-- Extracting version information from git describe...
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.16") found components: doxygen dot 
-- Using install prefix: /usr/local
-- Building for version: v1.2-7-gbcffccf8 / 1.0.0git
-- No C++ unit tests... skipping
-- 
-- Checking for module SWIG
-- Disabling SWIG because version check failed.
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found version "3.8.2") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/allisonogechukwu/projectDSA/gr-pdu_utils/build

**Comment by AllisonOge** [comment]
@jacobgilbert-snl after a proper library upgrade I have built it properly with gcc 10.1. Thanks and sorry for the inconveniences

**Comment by AllisonOge** [comment]
@jacobgilbert-snl after a proper library upgrade I have built it properly with gcc 10.1. Thanks and sorry for the inconveniences

**Comment by jacobgilbert-snl** [comment]
No problem. I appreciate you reporting it and the solution for you.
