### ISSUE TITLE
Build not honoring ENABLE_PYTHON=OFF

### ISSUE THREAD

**Issue by boogachamp** [sandialabs/gr-pdu_utils#4]
When disabling Python/Swig gnuradio support the build fails.

Used cmake -DENABLE_PYTHON:BOOL=OFF flag to set

Fixed locally by wrapping the addition of subdirectories:

if (ENABLE_PYTHON)
  add_subdirectory(swig)
  add_subdirectory(python)
endif(ENABLE_PYTHON)

**Comment by jacobgilbert-snl** [comment]
Thanks Bill. I have been meaning to update some of the older cmake to more current templates.

**Comment by jacobgilbert-snl** [comment]
Valid issue, updated as of db21fd6809071d3f0ab77f54e8eced0c3ec54295
